"""
streaming/alert_stream.py — Security Alert Feed (ws /stream/alerts)

Streams real-time security alerts generated by the detection engine:
  - privilege escalation detected
  - token abuse detected
  - rare role usage
  - replay divergence
"""
from __future__ import annotations

import asyncio
import logging
from typing import Any, Dict

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from .connection_manager import ConnectionManager

logger = logging.getLogger("hollowpurple.streaming.alerts")

router = APIRouter()
alert_manager = ConnectionManager()


@router.websocket("/alerts")
async def alert_stream(websocket: WebSocket):
    """
    Subscribe to the real-time security alert feed.

    Messages:
        { "type": "security_alert", "data": { "identity": ..., "severity": ..., ... } }
        { "type": "replay_divergence", "data": { "job_id": ..., "divergence_count": ... } }
    """
    await alert_manager.connect(websocket, channel="alerts")
    logger.info("client_subscribed", extra={"channel": "alerts"})
    try:
        while True:
            await asyncio.wait_for(websocket.receive_text(), timeout=30)
    except (WebSocketDisconnect, asyncio.TimeoutError):
        pass
    finally:
        await alert_manager.disconnect(websocket, channel="alerts")


async def broadcast_alert(alert: Dict[str, Any]) -> None:
    """Called by pattern detector / Mahoragha when a new alert fires."""
    await alert_manager.broadcast_channel("alerts", {"type": "security_alert", "data": alert})